# Generated by Django 3.0.8 on 2022-01-28 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
        ('Taxista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperativas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cooperativa', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.TextField()),
                ('ingresar_cobro', models.BooleanField(default=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Usuario.Personas')),
            ],
        ),
        migrations.CreateModel(
            name='CoopeTaxis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cooperativas', to='Cooperativa.Cooperativas')),
                ('taxista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxista', to='Taxista.Taxistas')),
            ],
        ),
    ]
