# Generated by Django 3.0.8 on 2022-01-28 21:58

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=75, unique=True)),
                ('clave', fernet_fields.fields.EncryptedTextField()),
                ('habilitado', models.BooleanField(default=True)),
                ('conf_correo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolesUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='Usuario.Roles')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='Usuario.Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('cedula', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
                ('foto_perfil', models.ImageField(null=True, upload_to='Perfiles')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Usuario.Usuarios')),
            ],
        ),
    ]
