# Generated by Django 3.0.8 on 2022-01-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='Perfiles'),
        ),
    ]
