# Generated by Django 3.0.8 on 2022-02-01 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_auto_20220128_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Usuario.Usuarios'),
        ),
    ]
