# Generated by Django 3.0.8 on 2022-02-01 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicio', '0001_initial'),
        ('Seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencias',
            name='servicio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Servicio.Servicios'),
        ),
    ]
