# Generated by Django 3.0.8 on 2022-01-28 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
        ('Taxista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitud_cliente', models.FloatField()),
                ('latitud_cliente', models.FloatField()),
                ('longitud_destino', models.FloatField()),
                ('latitud_destino', models.FloatField()),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('aceptada_tx', models.BooleanField(default=False)),
                ('rechazada', models.BooleanField(default=False)),
                ('culminada_tx', models.BooleanField(default=False)),
                ('valor_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='Cliente.Clientes')),
                ('taxista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxistas', to='Taxista.Taxistas')),
            ],
        ),
    ]
