# Generated by Django 3.0.8 on 2022-01-28 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxistas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_cedula_f', models.ImageField(upload_to='Taxistas')),
                ('foto_cedula_t', models.ImageField(upload_to='Taxistas')),
                ('numero_placa', models.CharField(max_length=8)),
                ('foto_vehiculo', models.ImageField(upload_to='Taxistas')),
                ('foto_matricula_f', models.ImageField(upload_to='Taxistas')),
                ('foto_matricula_t', models.ImageField(upload_to='Taxistas')),
                ('foto_licencia_f', models.ImageField(upload_to='Taxistas')),
                ('foto_licencia_t', models.ImageField(upload_to='Taxistas')),
                ('disponibilidad', models.CharField(max_length=22)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Usuario.Personas')),
            ],
        ),
    ]
