# Generated by Django 3.0.8 on 2022-02-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxista', '0002_auto_20220201_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxistas',
            name='foto_cedula_f',
            field=models.ImageField(blank=True, null=True, upload_to='Taxistas'),
        ),
        migrations.AlterField(
            model_name='taxistas',
            name='foto_cedula_t',
            field=models.ImageField(blank=True, null=True, upload_to='Taxistas'),
        ),
        migrations.AlterField(
            model_name='taxistas',
            name='foto_licencia_f',
            field=models.ImageField(blank=True, null=True, upload_to='Taxistas'),
        ),
        migrations.AlterField(
            model_name='taxistas',
            name='foto_licencia_t',
            field=models.ImageField(blank=True, null=True, upload_to='Taxistas'),
        ),
        migrations.AlterField(
            model_name='taxistas',
            name='foto_matricula_f',
            field=models.ImageField(blank=True, null=True, upload_to='Taxistas'),
        ),
        migrations.AlterField(
            model_name='taxistas',
            name='foto_matricula_t',
            field=models.ImageField(blank=True, null=True, upload_to='Taxistas'),
        ),
        migrations.AlterField(
            model_name='taxistas',
            name='foto_vehiculo',
            field=models.ImageField(blank=True, null=True, upload_to='Taxistas'),
        ),
    ]
